//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace huggle3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("huggle3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                    Arabic
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       أضف
        ///apply:                     طبِّق
        ///cancel:                    ألغِ
        ///clear:                     امحُ
        ///close:                     أغلق
        ///continue:                  واصل
        ///copy:                      انسخ
        ///delete:                    احذف
        ///error:                     خطأ
        ///exit:                      خروج
        ///minimizewindow:            تصغير
        ///no:                        لا
        ///ok:                        موافق
        ///remove:    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Български
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Добавяне
        ///apply:                     Apply
        ///cancel:                    Отказване
        ///clear:                     Изчистване
        ///close:                     Затваряне
        ///continue:                  Продължаване
        ///copy:                      Копиране
        ///delete:                    Изтриване
        ///error:                     Грешка
        ///exit:                      Изход
        ///minimizewindow:            Minimize
        ///no:                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bg {
            get {
                return ResourceManager.GetString("bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Deutsch
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Hinzufügen
        ///apply:                     Übernehmen
        ///cancel:                    Abbrechen
        ///clear:                     Leeren
        ///close:                     Schließen
        ///continue:                  Weiter
        ///copy:                      Kopieren
        ///delete:                    Löschen
        ///error:                     Fehler
        ///exit:                      Beenden
        ///minimizewindow:            Minimieren
        ///no:                        N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects:
        ///    bg.wikipedia;http://bg.wikipedia.org/,
        ///    ca.wikipedia;http://ca.wikipedia.org/,
        ///    de.wikipedia;http://de.wikipedia.org/,
        ///    en.wikipedia;http://en.wikipedia.org/,
        ///    es.wikipedia;http://es.wikipedia.org/,
        ///	fr.wikipedia;http://fr.wikipedia.org/,
        ///    ko.wikipedia;http://ko.wikipedia.org/,
        ///    nl.wikipedia;http://nl.wikipedia.org/,
        ///    no.wikipedia;http://no.wikipedia.org/,
        ///    pt.wikipedia;http://pt.wikipedia.org/,
        ///	sv.wikipedia;http://sv.wikipedia.org/,
        ///	hi.wikipedia;http://hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLocalConfig {
            get {
                return ResourceManager.GetString("DefaultLocalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      English
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Add
        ///apply:                     Apply
        ///cancel:                    Cancel
        ///clear:                     Clear
        ///close:                     Close
        ///continue:                  Continue
        ///copy:                      Copy
        ///delete:                    Delete
        ///error:                     Error
        ///exit:                      Exit
        ///minimizewindow:            Minimize
        ///no:                        No
        ///ok:                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Español
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Añadir
        ///apply:                     Aplicar
        ///cancel:                    Cancelar
        ///clear:                     Borrar
        ///close:                     Cerrar
        ///continue:                  Continuar
        ///copy:                      Copiar
        ///delete:                    Borrar
        ///error:                     Error
        ///exit:                      Salir
        ///minimizewindow:            Minimizar
        ///no:                        No
        ///ok:          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{:Huggle/LocalizationHeader}}
        ///
        ///&lt;pre&gt;
        ///name:                      Persian
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       اضافه
        ///apply:                     اعمال کردن
        ///cancel:                    انصراف
        ///clear:                     پاک کردن
        ///close:                     بستن
        ///continue:                  ادامه
        ///copy:                      رونوشت
        ///delete:                    حذف
        ///error:                     خطا
        ///exit:                      خارج شدن
        ///minimizewindow:            کوچک نمایی
        ///no:            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Français
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Ajouter
        ///apply:                     Appliquer
        ///cancel:                    Annuler
        ///clear:                     Effacer
        ///close:                     Fermer
        ///continue:                  Continuer
        ///copy:                      Copier
        ///delete:                    Supprimer
        ///error:                     Erreur
        ///exit:                      Sortir
        ///minimizewindow:            Réduire
        ///no:                        Non
        ///ok:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                       हिंदी
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       जोड़ें
        ///apply:                     लागु करें
        ///cancel:                    रद्द करें
        ///clear:                     साफ़ करें
        ///close:                     बंद करें
        ///continue:                  जारी करें
        ///copy:                      अनुकृति करें
        ///delete:                    मिटाएँ
        ///error:                     विकल्प
        ///exit:                      निकास
        ///minimizewindow:            मिनिमैस
        ///no:                        नहीं [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap hugglelogo {
            get {
                object obj = ResourceManager.GetObject("hugglelogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;pre&gt;
        ///name:                      Italiano
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Add
        ///apply:                     Apply
        ///cancel:                    Cancel
        ///clear:                     Clear
        ///close:                     Close
        ///continue:                  Continue
        ///copy:                      Copy
        ///delete:                    Delete
        ///error:                     Error
        ///exit:                      Exit
        ///minimizewindow:            Minimize
        ///no:                        No
        ///ok:                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      日本語
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       追加
        ///apply:                     適用
        ///cancel:                    キャンセル
        ///clear:                     クリア
        ///close:                     閉じる
        ///continue:                  続ける
        ///copy:                      コピー
        ///delete:                    削除
        ///error:                     エラー
        ///exit:                      終了
        ///minimizewindow:            最小化
        ///no:                        いいえ
        ///ok:                        OK
        ///remove:                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;pre&gt;
        ///name:                      ქართული
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       ჩამატება
        ///apply:                     შესრულება
        ///cancel:                    გაუქმება
        ///clear:                     გაწმენდა
        ///close:                     დახურვა
        ///continue:                  გაგრძელება
        ///copy:                      ასლის შექმნა
        ///delete:                    წაშლა
        ///error:                     შეცდომა
        ///exit:                      გასვლა
        ///minimizewindow:            შემცირება
        ///no:                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ka {
            get {
                return ResourceManager.GetString("ka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      ಕನ್ನಡ
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Add
        ///apply:                     Apply
        ///cancel:                    Cancel
        ///clear:                     Clear
        ///close:                     Close
        ///continue:                  Continue
        ///copy:                      Copy
        ///delete:                    Delete
        ///error:                     Error
        ///exit:                      Exit
        ///minimizewindow:            Minimize
        ///no:                        No
        ///ok:                        O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kn {
            get {
                return ResourceManager.GetString("kn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{:Huggle/LocalizationHeader}}
        ///
        ///
        ///&lt;pre&gt;
        ///name:                      മലയാളം
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Add
        ///apply:                     Apply
        ///cancel:                    റദ്ദാക്കുക
        ///clear:                     Clear
        ///close:                     Close
        ///continue:                  Continue
        ///copy:                      Copy
        ///delete:                    Delete
        ///error:                     Error
        ///exit:                      Exit
        ///minimizewindow:            Minimize
        ///no:                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ml {
            get {
                return ResourceManager.GetString("ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                       मराठी
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Add
        ///apply:                     Apply
        ///cancel:                    Cancel
        ///clear:                     खोडा
        ///close:                     बंद
        ///continue:                  Continue
        ///copy:                      Copy
        ///delete:                    काढून टाका
        ///error:                     अडथळा
        ///exit:                      बाहेर जा
        ///minimizewindow:            Minimize
        ///no:                        नाही
        ///ok:                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mr {
            get {
                return ResourceManager.GetString("mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Nederlands (Dutch)
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Toevoegen
        ///apply:                     Toepassen
        ///cancel:                    Annuleren
        ///clear:                     Leegmaken
        ///close:                     Sluiten
        ///continue:                  Doorgaan
        ///copy:                      Kopiëren
        ///delete:                    Verwijderen
        ///error:                     Fout
        ///exit:                      Afsluiten
        ///minimizewindow:            Minimaliseren
        ///no:       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;pre&gt;
        ///name:                      Norsk
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Legg til
        ///apply:                     Lagre
        ///cancel:                    Avbryt
        ///clear:                     Fjern
        ///close:                     Avslutt
        ///continue:                  Fortsett
        ///copy:                      Kopier
        ///delete:                    Slett
        ///error:                     Feil
        ///exit:                      Gå ut
        ///minimizewindow:            Minimer vindu
        ///no:                        Nei
        ///ok:          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Occitan
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Apondètz
        ///apply:                     Aplicatz
        ///cancel:                    Anullacion
        ///clear:                     Desebucatz
        ///close:                     Tampar
        ///continue:                  Contunhatz
        ///copy:                      Copiatz
        ///delete:                    Suprimissètz
        ///error:                     Error
        ///exit:                      Sortissètz
        ///minimizewindow:            Minimizètz
        ///no:                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oc {
            get {
                return ResourceManager.GetString("oc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      ଓଡ଼ିଆ
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       ମିଶାଇବେ
        ///apply:                     ବ୍ୟବହାର କରିବେ
        ///cancel:                    ନାକଚ କରିବେ
        ///clear:                     ଲିଭାଇ ଦେବେ
        ///close:                     ବନ୍ଦ କରିବେ
        ///continue:                  ଚାଲୁରଖିବେ
        ///copy:                      ନକଲ କରିବେ
        ///delete:                    ଲିଭାଇଦେବେ
        ///error:                     ଭୁଲ
        ///exit:                      ବାହାରିବେ
        ///minimizewindow:            ଛୋଟ କରିବେ
        ///no:                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Portuguęs
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Adicionar
        ///apply:                     Aplicar
        ///cancel:                    Cancelar
        ///clear:                     Apagar
        ///close:                     Fechar
        ///continue:                  Continuar
        ///copy:                      Copiar
        ///delete:                    Eliminar
        ///error:                     Erro
        ///exit:                      Sair
        ///minimizewindow:            Minimizar
        ///no:                        Năo
        ///ok:    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{:Huggle/LocalizationHeader}}
        ///
        ///&lt;pre&gt;
        ///name:                      Português do Brasil
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Adicionar
        ///apply:                     Aplicar
        ///cancel:                    Cancelar
        ///clear:                     Limpar
        ///close:                     Fechar
        ///continue:                  Continuar
        ///copy:                      Copiar
        ///delete:                    Eliminar
        ///error:                     Erro
        ///exit:                      Sair
        ///minimizewindow:            Minim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pt_br {
            get {
                return ResourceManager.GetString("pt_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = ru =
        ///
        ///&lt;pre&gt;
        ///name:                      Русский
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       Добавить
        ///apply:                     Применить
        ///cancel:                    Отмена
        ///clear:                     Очистить
        ///close:                     Закрыть
        ///continue:                  Продолжить
        ///copy:                      Копировать
        ///delete:                    Удалить
        ///error:                     Ошибка
        ///exit:                      Выход
        ///minimizewindow:            Свернуть
        ///no:                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      Svenska
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                        Add
        ///apply:                     Apply
        ///cancel:                     Avbryt
        ///clear:                     Rensa
        ///close:                      Stäng
        ///continue:                  Fortsätt
        ///copy:                       Kopiera
        ///delete:                    Ta bort
        ///error:                      Error
        ///exit:                      Stäng
        ///minimizewindow:             Minimera
        ///no:                        Nej
        ///ok:            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sv {
            get {
                return ResourceManager.GetString("sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///name:                      中文（简体）
        ///&lt;/pre&gt;
        ///
        ///=== General ===
        ///&lt;pre&gt;
        ///add:                       添加
        ///apply:                     应用
        ///cancel:                    取消
        ///clear:                     清除
        ///close:                     关闭
        ///continue:                  继续
        ///copy:                      复制
        ///delete:                    删除
        ///error:                     错误
        ///exit:                      退出
        ///minimizewindow:            最小化
        ///no:                        否
        ///ok:                        确定
        ///remove:                    移除
        ///re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh {
            get {
                return ResourceManager.GetString("zh", resourceCulture);
            }
        }
    }
}
