'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Huggle.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property blob_anon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_anon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_blanked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blanked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_blocknote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blocknote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_bot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_bot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_ignored() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_ignored", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_me() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_me", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_none", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_redirect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_redirect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_replaced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_replaced", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_reported() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_reported", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_revert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_revert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_reverted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_reverted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_warn_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_warn_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_warn_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_warn_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blob_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property browser_add_tab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser_add_tab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property browser_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property browser_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property browser_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property browser_remove_tab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("browser_remove_tab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contribs_last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contribs_last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contribs_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contribs_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contribs_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contribs_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;pre&gt;
        '''name:                      Deutsch
        '''&lt;/pre&gt;
        '''
        '''=== General ===
        '''&lt;pre&gt;
        '''add:                       Hinzufügen
        '''apply:                     Übernehmen
        '''cancel:                    Abbrechen
        '''clear:                     Leeren
        '''close:                     Schließen
        '''continue:                  Weiter
        '''copy:                      Kopieren
        '''delete:                    Löschen
        '''error:                     Fehler
        '''exit:                      Beenden
        '''minimizewindow:            Minimieren
        '''no:                        N [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property de() As String
            Get
                Return ResourceManager.GetString("de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to projects:
        '''    bg.wikipedia;http://bg.wikipedia.org/,
        '''    de.wikipedia;http://de.wikipedia.org/,
        '''    en.wikipedia;http://en.wikipedia.org/,
        '''    es.wikipedia;http://es.wikipedia.org/,
        '''    no.wikipedia;http://no.wikipedia.org/,
        '''    pt.wikipedia;http://pt.wikipedia.org/,
        '''    ru.wikipedia;http://ru.wikipedia.org/,
        '''    test wiki;http://test.wikipedia.org/
        '''    
        '''project:en.wikipedia.
        '''</summary>
        Friend ReadOnly Property DefaultLocalConfig() As String
            Get
                Return ResourceManager.GetString("DefaultLocalConfig", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property diff_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diff_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diff_revert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diff_revert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diff_revert_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diff_revert_warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;pre&gt;
        '''name:                      English
        '''&lt;/pre&gt;
        '''
        '''=== General ===
        '''&lt;pre&gt;
        '''add:                       Add
        '''apply:                     Apply
        '''cancel:                    Cancel
        '''clear:                     Clear
        '''close:                     Close
        '''continue:                  Continue
        '''copy:                      Copy
        '''delete:                    Delete
        '''error:                     Error
        '''exit:                      Exit
        '''minimizewindow:            Minimize
        '''no:                        No
        '''ok:                        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property gradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history_last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history_last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property history_to_cur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history_to_cur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property huggle_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("huggle_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property huggle_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("huggle_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_tag_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_tag_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_unwatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_unwatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_watch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_watch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;pre&gt;
        '''name:                      Português
        '''&lt;/pre&gt;
        '''
        '''=== General ===
        '''&lt;pre&gt;
        '''add:                       Adicionar
        '''apply:                     Aplicar
        '''cancel:                    Cancelar
        '''clear:                     Apagar
        '''close:                     Fechar
        '''continue:                  Continuar
        '''copy:                      Copiar
        '''delete:                    Eliminar
        '''error:                     Erro
        '''exit:                      Sair
        '''minimizewindow:            Minimizar
        '''no:                        Não
        '''ok:    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property pt() As String
            Get
                Return ResourceManager.GetString("pt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property revision_sight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("revision_sight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sight_and_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sight_and_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tri_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tri_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tri_none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tri_none", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tri_yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tri_yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_message", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_talk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_talk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_unwhitelist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_unwhitelist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_whitelist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_whitelist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to b	^block(ed)?$
        '''b	[dtv][5-7]$
        '''b	test ?[5-7]
        '''b	notification: blocked
        '''b	(you have|your ip address has) been (temporarily )?blocked
        '''b	block notice
        '''b	\+block
        '''b	\+?(anon|indef|vandal|username) ?block(ed)?
        '''b	temporary block
        '''b	due to recent vandalism from this account, it has been blocked
        '''
        '''n	orphaned fair use image tagging
        '''n	warning: image missing (fair use rationale|source information)
        '''n	(may|is going to) be deleted
        '''n	(cat|prod|proposed|speedy) (delete|deletion)? ?(nomination|notice|of|warning)
        '''n	se [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WarningSummaries() As String
            Get
                Return ResourceManager.GetString("WarningSummaries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;$PAGE&lt;/title&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;$PATHskins-1.5/common/shared.css&quot; type=&quot;text/css&quot; /&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;$PATHskins-1.5/monobook/main.css&quot; type=&quot;text/css&quot; /&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;$PATHw/index.php?title=MediaWiki:Common.css&amp;usemsgcache=yes&amp;ctype=text/css&amp;action=raw&quot; type=&quot;text/css&quot; /&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;$PATHw/index.php?title=MediaWiki:Monobook.css&amp;usemsgcache=yes&amp;ctype=text/css&amp;action=raw&quot; type=&quot;text/css&quot; /&gt;
        '''&lt;link rel=&quot;stylesheet&quot; href=&quot;$PATH [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WikiPageHtml() As String
            Get
                Return ResourceManager.GetString("WikiPageHtml", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
