// This file has been generated by the GUI designer. Do not modify.
namespace huggle3.Forms
{
    public partial class About
    {
        private global::Gtk.VBox vbox1;
        private global::Gtk.Image image1;
        private global::Gtk.Label label2;
        private global::Gtk.Label label1;
        private global::Gtk.Label label3;
        
        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget huggle3.Forms.About
            this.Name = "huggle3.Forms.About";
            this.Title = global::Mono.Unix.Catalog.GetString ("About");
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child huggle3.Forms.About.Gtk.Container+ContainerChild
            this.vbox1 = new global::Gtk.VBox ();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.image1 = new global::Gtk.Image ();
            this.image1.Name = "image1";
            this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("huggle3.Pictures.huggle3_newlogo.png");
            this.vbox1.Add (this.image1);
            global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label2 = new global::Gtk.Label ();
            this.label2.Name = "label2";
            this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Huggle is a Windows application for dealing with vandalism on Wikipedia.");
            this.label2.Wrap = true;
            this.label2.Justify = ((global::Gtk.Justification)(2));
            this.vbox1.Add (this.label2);
            global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new global::Gtk.Label ();
            this.label1.Name = "label1";
            this.label1.LabelProp = global::Mono.Unix.Catalog.GetString (@"Use of this application is subject to Wikipedia policies and guidelines. Responsibility for edits rests with the owner of the account. Please read the documentation before using this application. Huggle is licensed under GNU GPL as free software.

Contains images available under the terms of the GNU Lesser General Public License; see details.
");
            this.label1.Wrap = true;
            this.label1.Justify = ((global::Gtk.Justification)(2));
            this.vbox1.Add (this.label1);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label3 = new global::Gtk.Label ();
            this.label3.Name = "label3";
            this.label3.LabelProp = global::Mono.Unix.Catalog.GetString (@"<b>Current Contributors</b>
<a href=""http://meta.wikimedia.org/wiki/User:Addshore"">Addshore</a>
<a href=""http://en.wikipedia.org/wiki/User:Petrb"">Petrb</a>

<b>Past Contributors</b>
For a list of past contributors please see <a href=""http://meta.wikimedia.org/wiki/Huggle/Members"">this list</a>.");
			this.label3.UseMarkup = true;
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 407;
			this.DefaultHeight = 454;
			this.Show ();
		}
	}
}