
// This file has been generated by the GUI designer. Do not modify.
namespace huggle3.Forms
{
	public partial class Login
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget huggle3.Forms.Login
			this.Name = "huggle3.Forms.Login";
			this.Title = global::Mono.Unix.Catalog.GetString ("Login");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
