
// This file has been generated by the GUI designer. Do not modify.
namespace huggle3.Controls
{
    public partial class EditItem
    {
        /*protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget huggle3.Controls.EditItem
            global::Stetic.BinContainer.Attach (this);
            this.Name = "huggle3.Controls.EditItem";
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.Hide ();
        } */
    }
}
