
// This file has been generated by the GUI designer. Do not modify.
namespace huggle3.Forms
{
    public partial class HuggleForm
    {
        private global::Gtk.UIManager UIManager;
        private global::Gtk.Action MainSystemAction;
        private global::Gtk.Action HelpAction;
        private global::Gtk.Action MainSystemMessagesAction;
        private global::Gtk.Action Action;
        private global::Gtk.Action MainSystemOptionsAction;
        private global::Gtk.Action MainSystemExitAction;
        private global::Gtk.Action MainQueueAction;
        private global::Gtk.Action MainGotoAction;
        private global::Gtk.Action MainRevisionAction;
        private global::Gtk.Action MainPageAction;
        private global::Gtk.Action MainUserAction;
        private global::Gtk.Action MainBrowserAction;
        private global::Gtk.Action MainQueueNextAction;
        private global::Gtk.Action MainQueueClearAction;
        private global::Gtk.Action MainQueueTrimAction;
        private global::Gtk.Action MainQueueClearAllAction;
        private global::Gtk.Action MainQueueOptionsAction;
        private global::Gtk.Action MainGotoTalkAction;
        private global::Gtk.Action MainGotoMyContAction;
        private global::Gtk.Action MainRevisionViewAction;
        private global::Gtk.Action MainRevisionRevertAction;
        private global::Gtk.Action MainRevisionGoodAction;
        private global::Gtk.Action MainRevisionSightAction;
        private global::Gtk.Action MainRevisionPreviousAction;
        private global::Gtk.Action MainRevisionNextAction;
        private global::Gtk.Action MainRevisionLatestAction;
        private global::Gtk.Action MainPageSwitchtotalkAction;
        private global::Gtk.Action MainPageViewlatestAction;
        private global::Gtk.Action MainPageHistoryAction;
        private global::Gtk.Action MainPageHistorypageAction;
        private global::Gtk.Action MainPageEditAction;
        private global::Gtk.Action MainPageTagAction;
        private global::Gtk.Action MainUserShowAction;
        private global::Gtk.Action MainUserIgnoreAction;
        private global::Gtk.Action goBackAction;
        private global::Gtk.Action goForwardAction;
        private global::Gtk.VBox vbox1;
        private global::Gtk.MenuBar menubar1;
        private global::Gtk.Toolbar toolbar1;
        private global::Gtk.Toolbar toolbar2;
        private global::Gtk.HPaned hpaned1;
        private global::huggle3.Controls.QueuePanel queuepanel1;
        private global::Gtk.VPaned vpaned1;
        private global::Gtk.ScrolledWindow GtkScrolledWindow;
        private global::Gtk.TextView textview1;
        private global::Gtk.Statusbar statusbar1;
        
        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget huggle3.Forms.HuggleForm
            this.UIManager = new global::Gtk.UIManager ();
            global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
            this.MainSystemAction = new global::Gtk.Action ("MainSystemAction", global::Mono.Unix.Catalog.GetString ("[[main-system]]"), null, null);
            this.MainSystemAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
            w1.Add (this.MainSystemAction, null);
            this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
            this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
            w1.Add (this.HelpAction, null);
            this.MainSystemMessagesAction = new global::Gtk.Action ("MainSystemMessagesAction", global::Mono.Unix.Catalog.GetString ("[[main-system-messages]]"), null, null);
            this.MainSystemMessagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show new messages");
            w1.Add (this.MainSystemMessagesAction, null);
            this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("-"), null, null);
            this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
            w1.Add (this.Action, null);
            this.MainSystemOptionsAction = new global::Gtk.Action ("MainSystemOptionsAction", global::Mono.Unix.Catalog.GetString ("[[main-system-options]]"), null, null);
            this.MainSystemOptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
            w1.Add (this.MainSystemOptionsAction, null);
            this.MainSystemExitAction = new global::Gtk.Action ("MainSystemExitAction", global::Mono.Unix.Catalog.GetString ("[[main-system-exit]]"), null, null);
            this.MainSystemExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
            w1.Add (this.MainSystemExitAction, null);
            this.MainQueueAction = new global::Gtk.Action ("MainQueueAction", global::Mono.Unix.Catalog.GetString ("[[main-queue]]"), null, null);
            this.MainQueueAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue]]");
            w1.Add (this.MainQueueAction, null);
            this.MainGotoAction = new global::Gtk.Action ("MainGotoAction", global::Mono.Unix.Catalog.GetString ("[[main-goto]]"), null, null);
            this.MainGotoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-goto]]");
            w1.Add (this.MainGotoAction, null);
            this.MainRevisionAction = new global::Gtk.Action ("MainRevisionAction", global::Mono.Unix.Catalog.GetString ("[[main-revision]]"), null, null);
            this.MainRevisionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision]]");
            w1.Add (this.MainRevisionAction, null);
            this.MainPageAction = new global::Gtk.Action ("MainPageAction", global::Mono.Unix.Catalog.GetString ("[[main-page]]"), null, null);
            this.MainPageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page]]");
            w1.Add (this.MainPageAction, null);
            this.MainUserAction = new global::Gtk.Action ("MainUserAction", global::Mono.Unix.Catalog.GetString ("[[main-user]]"), null, null);
            this.MainUserAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-user]]");
            w1.Add (this.MainUserAction, null);
            this.MainBrowserAction = new global::Gtk.Action ("MainBrowserAction", global::Mono.Unix.Catalog.GetString ("[[main-browser]]"), null, null);
            this.MainBrowserAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-browser]]");
            w1.Add (this.MainBrowserAction, null);
            this.MainQueueNextAction = new global::Gtk.Action ("MainQueueNextAction", global::Mono.Unix.Catalog.GetString ("[[main-queue-next]]"), null, null);
            this.MainQueueNextAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue-next]]");
            w1.Add (this.MainQueueNextAction, null);
            this.MainQueueClearAction = new global::Gtk.Action ("MainQueueClearAction", global::Mono.Unix.Catalog.GetString ("[[main-queue-clear]]"), null, null);
            this.MainQueueClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue-clear]]");
            w1.Add (this.MainQueueClearAction, null);
            this.MainQueueTrimAction = new global::Gtk.Action ("MainQueueTrimAction", global::Mono.Unix.Catalog.GetString ("[[main-queue-trim]]"), null, null);
            this.MainQueueTrimAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue-trim]]");
            w1.Add (this.MainQueueTrimAction, null);
            this.MainQueueClearAllAction = new global::Gtk.Action ("MainQueueClearAllAction", global::Mono.Unix.Catalog.GetString ("[[main-queue-clear-all]]"), null, null);
            this.MainQueueClearAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue-clear-all]]");
            w1.Add (this.MainQueueClearAllAction, null);
            this.MainQueueOptionsAction = new global::Gtk.Action ("MainQueueOptionsAction", global::Mono.Unix.Catalog.GetString ("[[main-queue-options]]"), null, null);
            this.MainQueueOptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-queue-options]]");
            w1.Add (this.MainQueueOptionsAction, null);
            this.MainGotoTalkAction = new global::Gtk.Action ("MainGotoTalkAction", global::Mono.Unix.Catalog.GetString ("[[main-goto-talk]]"), null, null);
            this.MainGotoTalkAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-goto-talk]]");
            w1.Add (this.MainGotoTalkAction, null);
            this.MainGotoMyContAction = new global::Gtk.Action ("MainGotoMyContAction", global::Mono.Unix.Catalog.GetString ("[[main-goto-my-cont]]"), null, null);
            this.MainGotoMyContAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-goto-my-cont]]");
            w1.Add (this.MainGotoMyContAction, null);
            this.MainRevisionViewAction = new global::Gtk.Action ("MainRevisionViewAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-view]]"), null, null);
            this.MainRevisionViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-view]]");
            w1.Add (this.MainRevisionViewAction, null);
            this.MainRevisionRevertAction = new global::Gtk.Action ("MainRevisionRevertAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-revert]]"), null, null);
            this.MainRevisionRevertAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-revert]]");
            w1.Add (this.MainRevisionRevertAction, null);
            this.MainRevisionGoodAction = new global::Gtk.Action ("MainRevisionGoodAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-good]]"), null, null);
            this.MainRevisionGoodAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-good]]");
            w1.Add (this.MainRevisionGoodAction, null);
            this.MainRevisionSightAction = new global::Gtk.Action ("MainRevisionSightAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-sight]]"), null, null);
            this.MainRevisionSightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-sight]]");
            w1.Add (this.MainRevisionSightAction, null);
            this.MainRevisionPreviousAction = new global::Gtk.Action ("MainRevisionPreviousAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-previous]]"), null, null);
            this.MainRevisionPreviousAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-previous]]");
            w1.Add (this.MainRevisionPreviousAction, null);
            this.MainRevisionNextAction = new global::Gtk.Action ("MainRevisionNextAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-next]]"), null, null);
            this.MainRevisionNextAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-next]]");
            w1.Add (this.MainRevisionNextAction, null);
            this.MainRevisionLatestAction = new global::Gtk.Action ("MainRevisionLatestAction", global::Mono.Unix.Catalog.GetString ("[[main-revision-latest]]"), null, null);
            this.MainRevisionLatestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-revision-latest]]");
            w1.Add (this.MainRevisionLatestAction, null);
            this.MainPageSwitchtotalkAction = new global::Gtk.Action ("MainPageSwitchtotalkAction", global::Mono.Unix.Catalog.GetString ("[[main-page-switchtotalk]]"), null, null);
            this.MainPageSwitchtotalkAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-switchtotalk]]");
            w1.Add (this.MainPageSwitchtotalkAction, null);
            this.MainPageViewlatestAction = new global::Gtk.Action ("MainPageViewlatestAction", global::Mono.Unix.Catalog.GetString ("[[main-page-viewlatest]]"), null, null);
            this.MainPageViewlatestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-viewlatest]]");
            w1.Add (this.MainPageViewlatestAction, null);
            this.MainPageHistoryAction = new global::Gtk.Action ("MainPageHistoryAction", global::Mono.Unix.Catalog.GetString ("[[main-page-history]]"), null, null);
            this.MainPageHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-history]]");
            w1.Add (this.MainPageHistoryAction, null);
            this.MainPageHistorypageAction = new global::Gtk.Action ("MainPageHistorypageAction", global::Mono.Unix.Catalog.GetString ("[[main-page-historypage]]"), null, null);
            this.MainPageHistorypageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-historypage]]");
            w1.Add (this.MainPageHistorypageAction, null);
            this.MainPageEditAction = new global::Gtk.Action ("MainPageEditAction", global::Mono.Unix.Catalog.GetString ("[[main-page-edit]]"), null, null);
            this.MainPageEditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-edit]]");
            w1.Add (this.MainPageEditAction, null);
            this.MainPageTagAction = new global::Gtk.Action ("MainPageTagAction", global::Mono.Unix.Catalog.GetString ("[[main-page-tag]]"), null, null);
            this.MainPageTagAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-page-tag]]");
            w1.Add (this.MainPageTagAction, null);
            this.MainUserShowAction = new global::Gtk.Action ("MainUserShowAction", global::Mono.Unix.Catalog.GetString ("[[main-user-show]]"), null, null);
            this.MainUserShowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-user-show]]");
            w1.Add (this.MainUserShowAction, null);
            this.MainUserIgnoreAction = new global::Gtk.Action ("MainUserIgnoreAction", global::Mono.Unix.Catalog.GetString ("[[main-user-ignore]]"), null, null);
            this.MainUserIgnoreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("[[main-user-ignore]]");
            w1.Add (this.MainUserIgnoreAction, null);
            this.goBackAction = new global::Gtk.Action ("goBackAction", null, null, "gtk-go-back");
            w1.Add (this.goBackAction, null);
            this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
            w1.Add (this.goForwardAction, null);
            this.UIManager.InsertActionGroup (w1, 0);
            this.AddAccelGroup (this.UIManager.AccelGroup);
            this.Name = "huggle3.Forms.HuggleForm";
            this.Title = global::Mono.Unix.Catalog.GetString ("HuggleForm");
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child huggle3.Forms.HuggleForm.Gtk.Container+ContainerChild
            this.vbox1 = new global::Gtk.VBox ();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'MainSystemAction\' action=\'MainSystemActi" +
                "on\'><menuitem name=\'MainSystemMessagesAction\' action=\'MainSystemMessagesAction\'/" +
                "><separator/><menuitem name=\'MainSystemOptionsAction\' action=\'MainSystemOptionsA" +
                "ction\'/><menuitem name=\'MainSystemExitAction\' action=\'MainSystemExitAction\'/></m" +
                "enu><menu name=\'MainQueueAction\' action=\'MainQueueAction\'><menuitem name=\'MainQu" +
                "eueNextAction\' action=\'MainQueueNextAction\'/><separator/><menuitem name=\'MainQue" +
                "ueTrimAction\' action=\'MainQueueTrimAction\'/><menuitem name=\'MainQueueClearAction" +
                "\' action=\'MainQueueClearAction\'/><menuitem name=\'MainQueueClearAllAction\' action" +
                "=\'MainQueueClearAllAction\'/><menuitem name=\'MainQueueOptionsAction\' action=\'Main" +
                "QueueOptionsAction\'/></menu><menu name=\'MainGotoAction\' action=\'MainGotoAction\'>" +
                "<menuitem name=\'MainGotoTalkAction\' action=\'MainGotoTalkAction\'/><menuitem name=" +
                "\'MainGotoMyContAction\' action=\'MainGotoMyContAction\'/></menu><menu name=\'MainRev" +
                "isionAction\' action=\'MainRevisionAction\'><menuitem name=\'MainRevisionViewAction\'" +
                " action=\'MainRevisionViewAction\'/><menuitem name=\'MainRevisionRevertAction\' acti" +
                "on=\'MainRevisionRevertAction\'/><menuitem name=\'MainRevisionGoodAction\' action=\'M" +
                "ainRevisionGoodAction\'/><menuitem name=\'MainRevisionSightAction\' action=\'MainRev" +
                "isionSightAction\'/><separator/><menuitem name=\'MainRevisionPreviousAction\' actio" +
                "n=\'MainRevisionPreviousAction\'/><menuitem name=\'MainRevisionNextAction\' action=\'" +
                "MainRevisionNextAction\'/><menuitem name=\'MainRevisionLatestAction\' action=\'MainR" +
                "evisionLatestAction\'/></menu><menu name=\'MainPageAction\' action=\'MainPageAction\'" +
                "><menuitem name=\'MainPageSwitchtotalkAction\' action=\'MainPageSwitchtotalkAction\'" +
                "/><separator/><menuitem name=\'MainPageViewlatestAction\' action=\'MainPageViewlate" +
                "stAction\'/><menuitem name=\'MainPageHistoryAction\' action=\'MainPageHistoryAction\'" +
                "/><menuitem name=\'MainPageHistorypageAction\' action=\'MainPageHistorypageAction\'/" +
                "><separator/><menuitem name=\'MainPageEditAction\' action=\'MainPageEditAction\'/><m" +
                "enuitem name=\'MainPageTagAction\' action=\'MainPageTagAction\'/></menu><menu name=\'" +
                "MainUserAction\' action=\'MainUserAction\'><menuitem name=\'MainUserShowAction\' acti" +
                "on=\'MainUserShowAction\'/><menuitem name=\'MainUserIgnoreAction\' action=\'MainUserI" +
                "gnoreAction\'/></menu><menu name=\'MainBrowserAction\' action=\'MainBrowserAction\'/>" +
                "<menu name=\'HelpAction\' action=\'HelpAction\'/></menubar></ui>");
            this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add (this.menubar1);
            global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'/></ui>");
            this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.vbox1.Add (this.toolbar1);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar2\'><toolitem name=\'goBackAction\' action=\'goBackAction\'/" +
                "><toolitem name=\'goForwardAction\' action=\'goForwardAction\'/></toolbar></ui>");
            this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
            this.toolbar2.Name = "toolbar2";
            this.toolbar2.ShowArrow = false;
            this.vbox1.Add (this.toolbar2);
            global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar2]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hpaned1 = new global::Gtk.HPaned ();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 68;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.queuepanel1 = null;
            this.hpaned1.Add (this.queuepanel1);
            global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.queuepanel1]));
            w5.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vpaned1 = new global::Gtk.VPaned ();
            this.vpaned1.CanFocus = true;
            this.vpaned1.Name = "vpaned1";
            this.vpaned1.Position = 215;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.textview1 = new global::Gtk.TextView ();
            this.textview1.CanFocus = true;
            this.textview1.Name = "textview1";
            this.GtkScrolledWindow.Add (this.textview1);
            this.vpaned1.Add (this.GtkScrolledWindow);
            this.hpaned1.Add (this.vpaned1);
            this.vbox1.Add (this.hpaned1);
            global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
            w9.Position = 3;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new global::Gtk.Statusbar ();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add (this.statusbar1);
            global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
            w10.Position = 4;
            w10.Expand = false;
            w10.Fill = false;
            this.Add (this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 936;
            this.DefaultHeight = 500;
            this.Show ();
        }
    }
}
