
// This file has been generated by the GUI designer. Do not modify.
namespace huggle3
{
    public partial class Browser
    {
        /*protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget huggle3.Browser
            global::Stetic.BinContainer.Attach (this);
            this.Name = "huggle3.Browser";
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.Hide ();
        }*/
    }
}
